name: Release

on:
  push:
    branches: [ main ]
    paths: [ CHANGELOG.md ]
    
# TODO: use changie action after I make it
env:
  CHANGIE_VERSION: 1.9.0

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Changie
      uses: supplypike/setup-bin@v2
      with:
        uri: 'https://github.com/miniscruff/changie/releases/download/v{{ env.CHANGIE_VERSION }}/changie_{{ env.CHANGIE_VERSION }}_linux_amd64.tar.gz'
        name: 'changie'
        version: 'v{{ env.CHANGIE_VERSION }}'

    - name: Add env vars
      run: |
        echo VERSION=$(changie latest) >> $GITHUB_ENV
        echo RELEASE_NOTES_PATH=.changes/$(changie latest).md >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        body_path: ${{ env.RELEASE_NOTES_PATH }}
