name: unit test and coverage

on:
  push:
    branches: [ skip-for-now ]
  pull_request:
    branches: [ skip-for-now ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    defaults:
      run:
        shell: bash
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Install OS deps
      run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libgl1-mesa-dev libalut-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

    - name: Xvfb
      run: "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.29

    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Coverage
      uses: codecov/codecov-action@v2.1.0
      with:
        file: ./coverage.txt
        fail_ci_if_error: true

